# Generated by Django 3.2.8 on 2022-07-10 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0002_street'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contragent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Contragent name')),
                ('address_ur', models.TextField(blank=True, null=True, verbose_name='Legal address')),
                ('contragent_type', models.PositiveSmallIntegerField(choices=[(1, 'b2b'), (2, 'b2c')], db_index=True, verbose_name='Contragent type')),
                ('house', models.CharField(blank=True, max_length=50, null=True, verbose_name='House')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Edited date')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН')),
                ('okonh', models.CharField(blank=True, max_length=20, verbose_name='ОКОНХ')),
                ('okpo', models.CharField(blank=True, max_length=20, verbose_name='OKПO')),
                ('oked', models.CharField(blank=True, max_length=20, verbose_name='OКЭД')),
                ('code_nds', models.CharField(blank=True, max_length=20, verbose_name='РКП НДС')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.area', verbose_name='Area/City')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.country', verbose_name='Country')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.district', verbose_name='District')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.staff', verbose_name='Manager')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.region', verbose_name='Region')),
                ('street', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.street', verbose_name='Street')),
            ],
            options={
                'verbose_name': 'Contragent',
                'verbose_name_plural': 'Contragents',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Middle name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Phone number')),
                ('position', models.CharField(max_length=50, verbose_name='Position')),
                ('role', models.CharField(blank=True, max_length=50, null=True, verbose_name='Role')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birth day')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('contragent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contragents.contragent', verbose_name='Contragent')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
